apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: israelbalog01/cicd-test-app@sha256:e455a07cf89f45708e0d2e2257a77d8ee5b1e3415f9ffcf38690600745510464
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
