apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: israelbalog01/cicd-test-app:3ecffbe4ddf800aa16112bea4914d7fc6c6bedf6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
