apiVersion: v1
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tLyI6eyJ1c2VybmFtZSI6ImlzcmFlbGJhbG9nMDEiLCJwYXNzd29yZCI6IkdlZnJhbmllMjAwMSoiLCJlbWFpbCI6ImliYWxvZ0Bncm91cGVyZi5jb20iLCJhdXRoIjoiYVhOeVlXVnNZbUZzYjJjd01UcEhaV1p5WVc1cFpUSXdNREVxIn19fQ==
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
